# Dockerfile optimizado para FastAPI con MinIO

FROM python:3.11-slim

# Instalar dependencias esenciales
RUN apt-get update && \
    apt-get install -y gcc g++ make curl && \
    rm -rf /var/lib/apt/lists/*

# Crear y establecer el directorio de trabajo
WORKDIR /app
COPY . /app

# Instalar dependencias de Python
RUN pip install --upgrade pip && \
    pip install fastapi uvicorn minio pandas scikit-learn seaborn python-multipart joblib

# Exponer puerto para FastAPI
EXPOSE 8000

# Comando para ejecutar la aplicación FastAPI
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
