channels:
- conda-forge
dependencies:
- python=3.7.14
- pip<=22.2.2
- pip:
  - mlflow
  - cffi==1.15.1
  - colorama==0.4.5
  - distributed==2022.2.0
  - graphviz==0.20.1
  - lightgbm==4.6.0
  - matplotlib==3.5.3
  - pandas==1.3.5
  - pyarrow==6.0.1
  - scikit-learn==1.0.2
  - setproctitle==1.3.2
name: mlflow-env
